"""Report export helpers — JSON, CSV and a self-contained HTML report."""
from __future__ import annotations

import csv
import html
import io
import json
import os
from datetime import datetime, timezone
from typing import Any, Dict


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def to_json(data: Dict[str, Any], path: str) -> str:
    payload = {"tool": "VortexOSINT", "generated_at": _timestamp(), "data": data}
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False, default=str)
    return os.path.abspath(path)


def to_csv(rows: list[dict], path: str) -> str:
    if not rows:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("")
        return os.path.abspath(path)
    fieldnames = list({k for r in rows for k in r.keys()})
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return os.path.abspath(path)


def _render_value(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return f"<pre>{html.escape(json.dumps(value, indent=2, default=str))}</pre>"
    return html.escape(str(value))


def to_html(target: str, scan_type: str, data: Dict[str, Any], path: str) -> str:
    rows = io.StringIO()
    for section, payload in data.items():
        rows.write(f"<h2>{html.escape(str(section))}</h2><table>")
        if isinstance(payload, dict):
            for k, v in payload.items():
                rows.write(f"<tr><th>{html.escape(str(k))}</th><td>{_render_value(v)}</td></tr>")
        else:
            rows.write(f"<tr><td>{_render_value(payload)}</td></tr>")
        rows.write("</table>")

    document = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VortexOSINT Report — {html.escape(target)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background:#0d1117; color:#e6edf3; }}
  header {{ padding: 28px; background: linear-gradient(135deg,#1f6feb,#8957e5); color:#fff; }}
  header h1 {{ margin:0; font-size: 22px; }}
  header p {{ margin: 6px 0 0; opacity: .85; font-size: 13px; }}
  main {{ padding: 24px; max-width: 980px; margin: 0 auto; }}
  h2 {{ border-bottom: 1px solid #30363d; padding-bottom: 6px; margin-top: 32px; }}
  table {{ width:100%; border-collapse: collapse; margin: 10px 0; }}
  th, td {{ text-align:left; padding: 8px 10px; border-bottom: 1px solid #21262d; vertical-align: top; }}
  th {{ width: 220px; color:#7ee787; font-weight:600; }}
  pre {{ white-space: pre-wrap; word-break: break-word; background:#161b22; padding:10px; border-radius:8px; margin:0; }}
  footer {{ padding: 18px 24px; color:#8b949e; font-size:12px; text-align:center; }}
</style></head>
<body>
<header><h1>\U0001F50D VortexOSINT Report</h1>
<p>Target: <strong>{html.escape(target)}</strong> &nbsp;·&nbsp; Scan: {html.escape(scan_type)} &nbsp;·&nbsp; {_timestamp()}</p></header>
<main>{rows.getvalue()}</main>
<footer>Generated by VortexOSINT — 100% free OSINT toolkit · Use only on authorized targets / your own assets.</footer>
</body></html>"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(document)
    return os.path.abspath(path)


def to_pdf(target: str, scan_type: str, data: Dict[str, Any], path: str) -> str:
    """Export a clean, paginated PDF report using reportlab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle)
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            "PDF export needs reportlab — install with: pip install reportlab"
        ) from exc

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "VortexTitle", parent=styles["Title"], textColor=colors.HexColor("#1f6feb"))
    h2 = ParagraphStyle(
        "VortexH2", parent=styles["Heading2"], textColor=colors.HexColor("#8957e5"))
    body = ParagraphStyle("VortexBody", parent=styles["BodyText"], fontSize=8.5, leading=11)

    doc = SimpleDocTemplate(path, pagesize=A4, title=f"VortexOSINT — {target}",
                            topMargin=18 * mm, bottomMargin=16 * mm)
    story = [
        Paragraph("VortexOSINT Report", title_style),
        Paragraph(
            f"Target: <b>{html.escape(target)}</b> &nbsp;·&nbsp; "
            f"Scan: {html.escape(scan_type)} &nbsp;·&nbsp; {_timestamp()}", body),
        Spacer(1, 8 * mm),
    ]

    def add_table(rows):
        if not rows:
            return
        tbl = Table(rows, colWidths=[55 * mm, 110 * mm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f7")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#24292f")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d0d7de")),
            ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.white, colors.HexColor("#f6f8fa")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(tbl)
        story.append(Spacer(1, 5 * mm))

    def flatten(value):
        if isinstance(value, (dict, list)):
            return json.dumps(value, indent=1, default=str)[:1500]
        return str(value)

    for section, payload in data.items():
        story.append(Paragraph(html.escape(str(section)), h2))
        rows = []
        if isinstance(payload, dict):
            for k, v in payload.items():
                if v in (None, "", [], {}):
                    continue
                rows.append([Paragraph(html.escape(str(k)), body),
                             Paragraph(html.escape(flatten(v)).replace("\n", "<br/>"), body)])
        else:
            rows.append([Paragraph("value", body),
                         Paragraph(html.escape(flatten(payload)), body)])
        add_table(rows)

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "<font size=7 color='#8b949e'>Generated by VortexOSINT — 100% free OSINT toolkit. "
        "Use only on authorized targets.</font>", body))
    doc.build(story)
    return os.path.abspath(path)
