"""Report export helpers — JSON, CSV and a self-contained HTML report."""
from __future__ import annotations

import csv
import html
import io
import json
import os
from datetime import datetime, timezone
from typing import Any, Dict


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def to_json(data: Dict[str, Any], path: str) -> str:
    payload = {"tool": "VortexOSINT", "generated_at": _timestamp(), "data": data}
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False, default=str)
    return os.path.abspath(path)


def to_csv(rows: list[dict], path: str) -> str:
    if not rows:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("")
        return os.path.abspath(path)
    fieldnames = list({k for r in rows for k in r.keys()})
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return os.path.abspath(path)


def _render_value(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return f"<pre>{html.escape(json.dumps(value, indent=2, default=str))}</pre>"
    return html.escape(str(value))


def to_html(target: str, scan_type: str, data: Dict[str, Any], path: str) -> str:
    rows = io.StringIO()
    for section, payload in data.items():
        rows.write(f"<h2>{html.escape(str(section))}</h2><table>")
        if isinstance(payload, dict):
            for k, v in payload.items():
                rows.write(f"<tr><th>{html.escape(str(k))}</th><td>{_render_value(v)}</td></tr>")
        else:
            rows.write(f"<tr><td>{_render_value(payload)}</td></tr>")
        rows.write("</table>")

    document = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VortexOSINT Report — {html.escape(target)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background:#0d1117; color:#e6edf3; }}
  header {{ padding: 28px; background: linear-gradient(135deg,#1f6feb,#8957e5); color:#fff; }}
  header h1 {{ margin:0; font-size: 22px; }}
  header p {{ margin: 6px 0 0; opacity: .85; font-size: 13px; }}
  main {{ padding: 24px; max-width: 980px; margin: 0 auto; }}
  h2 {{ border-bottom: 1px solid #30363d; padding-bottom: 6px; margin-top: 32px; }}
  table {{ width:100%; border-collapse: collapse; margin: 10px 0; }}
  th, td {{ text-align:left; padding: 8px 10px; border-bottom: 1px solid #21262d; vertical-align: top; }}
  th {{ width: 220px; color:#7ee787; font-weight:600; }}
  pre {{ white-space: pre-wrap; word-break: break-word; background:#161b22; padding:10px; border-radius:8px; margin:0; }}
  footer {{ padding: 18px 24px; color:#8b949e; font-size:12px; text-align:center; }}
</style></head>
<body>
<header><h1>🔍 VortexOSINT Report</h1>
<p>Target: <strong>{html.escape(target)}</strong> &nbsp;·&nbsp; Scan: {html.escape(scan_type)} &nbsp;·&nbsp; {_timestamp()}</p></header>
<main>{rows.getvalue()}</main>
<footer>Generated by VortexOSINT — 100% free OSINT toolkit · Use only on authorized targets / your own assets.</footer>
</body></html>"""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(document)
    return os.path.abspath(path)
